### ISSUE TITLE
Error! Can't parse WADL file.

### ISSUE THREAD

**Issue by Sicks3c** [dwisiswant0/wadl-dumper#23]
**Describe the bug**

This bugs occurs when the target has insecure SSL

**To Reproduce**

```bash
wadl-dumper -i "https://customerevents.us-east-1.internal.dradis.netflix.com/application.wadl?detail=true" -b
```

**Expected behavior**

Output all the possible paths in the wadl directory

**Screenshots**

![screenshot](https://i.imgur.com/Ufr5F2Y.png)

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- OS version: [uname -a]
- wadl-dumper Version: 

**Additional context**
Add any other context about the problem here. Full output log is probably a helpful thing to add here.

**Comment by dwisiswant0** [comment]
Hi, @Sicks3c. Sometimes, it happened because the dependencies can't parse response from URL. Try to download first then run wadl-dumper. Workaround:

1. `wget http://url/file.wadl`, then run dumper
2. `wadl-dumper -i file.wadl`

**Comment by Sicks3c** [comment]
Hi @dwisiswant0 

Thank you for fast reply
When I use the file method I only get the paths not the full url
![here](https://i.imgur.com/79sSQsY.png)

Instead of 
![here](https://i.imgur.com/8Rysalt.png)

Regards

**Comment by dwisiswant0** [comment]
> Hi @dwisiswant0 
> 
> Thank you for fast reply
> When I use the file method I only get the paths not the full url
> ![here](https://i.imgur.com/79sSQsY.png)
> 
> Instead of 
> ![here](https://i.imgur.com/8Rysalt.png)
> 
> Regards

Yea that because you don't use `-b` flag to print with base URL prefix. But it all depends on the source origin WADL file, some add the base URL directly or just an endpoint. For example if the 2nd URL (like your image) you download - and execute it like your first proof, the result will be same as your second proof (CMIIW).

Feel free to reopen this issue if you have more questions. 🙂
